### ISSUE TITLE
python/LocalPubSub: using a non-default component name breaks recipe.yaml

### ISSUE THREAD

**Issue by aws-kevinrickard** [aws-greengrass/aws-greengrass-component-templates#38]
**Describe the bug / steps to reproduce**
If you init the template with a non-default name (`Publisher` in this case):
```
gdk component init -t LocalPubSub -l python -n Publisher
```

then configure gdk-config.json and run `gdk component build`, it errors:
```
[2023-06-21 17:47:45] INFO - Getting project configuration from gdk-config.json
[2023-06-21 17:47:45] INFO - Found component recipe file 'recipe.yaml' in the  project directory.
[2023-06-21 17:47:45] INFO - Building the component 'com.example.PythonLocalPubSub' with the given project configuration.
[2023-06-21 17:47:45] INFO - Using 'zip' build system to build the component.
[2023-06-21 17:47:45] WARNING - This component is identified as using 'zip' build system. If this is incorrect, please exit and specify custom build command in the 'gdk-config.json'.
[2023-06-21 17:47:45] INFO - Zipping source code files of the component.
[2023-06-21 17:47:46] INFO - Copying over the build artifacts to the greengrass component artifacts build folder.
[2023-06-21 17:47:46] INFO - Updating artifact URIs in the recipe.
[2023-06-21 17:47:46] WARNING - Could not find the artifact file 'LocalPubSub.zip' in the build folder '{PosixPath('/greengrass/v2/dev_environment/Publisher/zip-build')}'.
[2023-06-21 17:47:46] INFO - Found credentials in environment variables.
[2023-06-21 17:47:47] ERROR - Could not find the artifact on S3.
An error occurred (403) when calling the HeadObject operation: Forbidden
[2023-06-21 17:47:47] ERROR - Failed to build the component with the given project configuration.

=============================== ERROR ===============================

[2023-06-21 17:47:47] ERROR - Could not find artifact with URI 's3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/LocalPubSub.zip' on s3 or inside the build folders.
Traceback (most recent call last):
  File "/home/kevin/.local/lib/python3.9/site-packages/gdk/CLIParser.py", line 188, in main
    parse_args_actions.run_command(args_namespace)
  File "/home/kevin/.local/lib/python3.9/site-packages/gdk/common/parse_args_actions.py", line 26, in run_command
    call_action_by_name(method_name, d_args)
  File "/home/kevin/.local/lib/python3.9/site-packages/gdk/common/parse_args_actions.py", line 46, in call_action_by_name
    method_to_call(d_args)
  File "/home/kevin/.local/lib/python3.9/site-packages/gdk/commands/methods.py", line 15, in _gdk_component_build
    component.build(d_args)
  File "/home/kevin/.local/lib/python3.9/site-packages/gdk/commands/component/component.py", line 10, in build
    BuildCommand(d_args).run()
  File "/home/kevin/.local/lib/python3.9/site-packages/gdk/commands/component/BuildCommand.py", line 60, in run
    self.default_build_component()
  File "/home/kevin/.local/lib/python3.9/site-packages/gdk/commands/component/BuildCommand.py", line 105, in default_build_component
    self.build_recipe_transformer.transform(self._get_build_folder_by_build_system())
  File "/home/kevin/.local/lib/python3.9/site-packages/gdk/commands/component/transformer/BuildRecipeTransformer.py", line 17, in transform
    self.update_component_recipe_file(component_recipe, build_folders)
  File "/home/kevin/.local/lib/python3.9/site-packages/gdk/commands/component/transformer/BuildRecipeTransformer.py", line 29, in update_component_recipe_file
    self.update_artifact_uris(parsed_component_recipe, build_folders)
  File "/home/kevin/.local/lib/python3.9/site-packages/gdk/commands/component/transformer/BuildRecipeTransformer.py", line 63, in update_artifact_uris
    raise Exception(
Exception: Could not find artifact with URI 's3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/LocalPubSub.zip' on s3 or inside the build folders.
```
^  because the recipe.yaml is hard-coded to the default name of `LocalPubSub`

**Expected behavior**
I expect it to know what I named my component and use that, like it does when zipping to Publisher.zip

**Actual behavior**
It doesn't use my component name, instead it expects the name to be LocalPubSub and in turn LocalPubSub.zip

**Environment**
 - OS: Linux raspberrypi 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux

**Workaround**
Update the recipe.yaml Manifests.Artifacts.Uri and Manifests.Lifecycle.Run to reference the component name instead of LocalPubSub

**Comment by MikeDombo** [comment]
Hi,

The build is currently based on the working directory rather than the component name. This has been updated to be optional in the development version which will be released in an upcoming update.

**Comment by aws-kevinrickard** [comment]
Thanks for the clarification and update!
